name: spring-microservices-auth
services:
  postgres:
    container_name: ms_auth_postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@321
      POSTGRES_DB: demo_auth
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
    ports:
      - "5433:5432"

volumes:
  postgres:
    driver: local
